CC=gcc
CFLAGS=-I.

#цель: зависимости
#[tab] команда
all : 
	gcc proc_mem.c -o proc_mem
	#./proc_mem

process_memory :
	gcc process_memory.c -o process_memory
	#./process_memory

clean :
	rm process_memory proc_mem